exports.up = function (knex) {
    let createQuery = `
            CREATE TABLE public.post_master (
                post_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                post_text varchar(400) NOT NULL,
                post_score integer NOT NULL,
                post_created_at timestamptz(0) NOT NULL,
                post_updated_at timestamptz(0) NOT NULL
            );
    `;
    return knex.raw(createQuery);
};

exports.down = function (knex) {
    let dropQuery = `DROP TABLE post_master`;
    return knex.raw(dropQuery);
};
