apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: amarnaththillai/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './**/*.js'
    - image: amarnaththillai/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './**/*.js'
    - image: amarnaththillai/feeds
      context: feeds
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './**/*.js'